# Generated by Django 4.2 on 2023-04-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcontact',
            name='icon',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
